spring:
  cloud:
    gateway:
      routes:
        # 路由配置的名称，必须保证在本应用中唯一
        - id: auth
          # 要将请求路由到的URI（lb表示负载均衡）
          uri: lb://city-farm-auth
          # 匹配条件，当本应用收到的请求满足条件时，将使用这个路由规则进行转发
          predicates:
            # 限定路径条件，此处为设置一个前缀匹配规则
            - Path=/auth/**
          filters:
            # 代理时，去掉本应用所收到的URI的前几个部分
            # 如：本应用收到/prefix/hello的请求，若不设置此参数，网关将会将收到的请求
            # 代理到指定微服务的/prefix/hello路径下
            # （server:8080/prefix/hello → server:8081/prefix/hello）
            #
            # 若设置StripPrefix=1，则将会把请求代理到指定微服务的/hello路径下，去掉了
            # 原本路径的前1个部分
            # （server:8080/prefix/hello → server:8081/hello）
            - StripPrefix=1